Can be executed but WIP
Numpy error:

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/home/sjk015/Documents/SKJ015-Intelligent_Control/Task_4_1/ros2_ws/install/pbvs_package/lib/pbvs_package/feature_extraction_node", line 33, in <module>
    sys.exit(load_entry_point('pbvs-package==0.0.0', 'console_scripts', 'feature_extraction_node')())
  File "/home/sjk015/Documents/SKJ015-Intelligent_Control/Task_4_1/ros2_ws/install/pbvs_package/lib/python3.10/site-packages/pbvs_package/FeatureExtractor.py", line 34, in main
    PBVS_feature_node = PBVS_FeatureNode()
  File "/home/sjk015/Documents/SKJ015-Intelligent_Control/Task_4_1/ros2_ws/install/pbvs_package/lib/python3.10/site-packages/pbvs_package/FeatureExtractor.py", line 15, in __init__
    self.declare_parameter('featureParams', [['1.', '1.', '-2.'], ['2.', '0.5'], ['-1.', '-1.', '2.']])
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/node.py", line 367, in declare_parameter
    return self.declare_parameters('', [args], ignore_override)[0]
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/node.py", line 465, in declare_parameters
    descriptor.type = Parameter.Type.from_parameter_value(value).value
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/parameter.py", line 68, in from_parameter_value
    raise TypeError(
TypeError: The given value is not a list of one of the allowed types '[['1.', '1.', '-2.'], ['2.', '0.5'], ['-1.', '-1.', '2.']]'.
[ros2run]: Process exited with failure 1